apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-set
  labels:
    app: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:latest
        ports:
        - containerPort: 5672
        volumeMounts:
        - mountPath: "/var/lib/rabbitmq/mnesia/"
          name: rabbitmq-disk
      volumes:
      - name: rabbitmq-disk
        persistentVolumeClaim:
          claimName: rabbitmq-claim
